on:
  release:
    types:
      - published

jobs:
  build_nvidia:
    runs-on: ubuntu-latest
    env:
      registry_url: quay.io/kvalin/gpu-monitoring-pmlogger
    steps:
      - name: See if release is latest
        run: |
          LATEST_TAG=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.tag_name')
          
          latest=0
          if [[ "$LATEST_TAG" == "${{ github.event.release.tag_name }}" ]]; then
            latest=1
          fi
          echo "LATEST_RELEASE"="$latest" >> $GITHUB_ENV

      - name: Set tags
        run: |
          tags="$registry_url:nvidia-${{ github.event.release.tag_name }}"

          if [[ "$LATEST_RELEASE" -eq 1 ]]; then
            tags="$tags,$registry_url:nvidia,$registry_url:latest"
          fi

          echo "TAGS"="$tags" >> $GITHUB_ENV

      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_UNAME }}
          password: ${{ secrets.QUAY_PASSWD }}


      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      - name: Build and push container
        uses: docker/build-push-action@v6
        with:
          file: Containerfile
          push: true
          tags: ${{ env.TAGS }}
